(function(g){var window=this;'use strict';var qhb=function(a){g.T.call(this,{G:"div",N:"ytp-inline-preview-ui"});this.Yf=!1;this.player=a;this.S(a,"onStateChange",this.gP);this.S(a,"videodatachange",this.pw);this.S(a,"onInlinePreviewModeChange",this.m4);this.mf=new g.Hp(this.Dv,null,this);g.D(this,this.mf)},x6=function(a){g.xT.call(this,a);
this.j=new qhb(this.player);g.D(this,this.j);this.j.hide();g.MS(this.player,this.j.element,4);if(a.isInline()){this.load();var b=a.getRootNode();g.Sp(b,["ytp-inline-preview-mode","ytp-no-contextmenu"]);this.player.T().K("web_inline_player_disable_scrubbing")&&g.Vp(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0)}};
g.w(qhb,g.T);g.k=qhb.prototype;
g.k.kM=function(){this.tooltip=new g.WV(this.player,this);g.D(this,this.tooltip);g.MS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Qc=new g.dU(this.player);g.D(this,this.Qc);this.Qj=new g.T({G:"div",Ia:["ytp-inline-preview-scrim"]});g.D(this,this.Qj);this.Qj.Ea(this.element);this.S(this.Qj.element,"click",this.PG);this.qj=new g.PV(this.player,this,300);g.D(this,this.qj);this.qj.Ea(this.Qj.element);this.controls=new g.T({G:"div",N:"ytp-inline-preview-controls"});g.D(this,this.controls);
this.controls.Ea(this.element);var a=new g.eV(this.player,this,this.player.T().K("kevlar_simp_remove_min_width_for_mute_button"));g.D(this,a);a.Ea(this.controls.element);a=new g.NV(this.player,this);g.D(this,a);a.Ea(this.controls.element);this.Jc=new g.lV(this.player,this);g.D(this,this.Jc);g.MS(this.player,this.Jc.element,4);this.S(this.player,"appresize",this.Cb);this.S(this.player,"fullscreentoggled",this.Cb);this.Cb()};
g.k.show=function(){g.Ip(this.mf);this.Yf||(this.kM(),this.Yf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Jc.show();this.player.Ma("onInlinePreviewUiReady")};
g.k.hide=function(){this.mf.stop();g.T.prototype.hide.call(this);this.player.isInline()||this.Yf&&this.Jc.hide()};
g.k.oa=function(){g.T.prototype.oa.call(this)};
g.k.PG=function(a){a.target===this.Qj.element&&this.player.Ma("onExpandInlinePreview",a)};
g.k.m4=function(){g.Vp(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Ge=function(){this.Jc.yc();this.qj.yc()};
g.k.Dv=function(){this.Ge();g.Ip(this.mf)};
g.k.Cb=function(){g.yV(this.Jc,0,this.player.jb().getPlayerSize().width,!1);g.mV(this.Jc)};
g.k.gP=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.pw=function(a,b){if(this.player.isInline()){g.Vp(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.MI);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Vp(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Hc=function(){return this.tooltip};
g.k.vg=function(){return!1};
g.k.gh=function(){return!1};
g.k.Sb=function(){return!1};
g.k.Ll=function(){return!1};
g.k.NH=function(){};
g.k.Np=function(){};
g.k.by=function(){};
g.k.Jm=function(){return null};
g.k.BF=function(){return null};
g.k.EF=function(){return new g.Fe(0,0)};
g.k.wk=function(){return new g.Om(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Qv=function(a,b,c,d,e){var f=d=0,h=0,l=g.bn(a);if(b){c=g.Qp(b,"ytp-mute-button");var m=g.Qp(b,"ytp-subtitles-button"),n=g.$m(b,this.element);b=g.bn(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.jb().getPlayerSize().width;h=g.ye(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.qp=function(){};
g.k.Fl=function(){return!1};
g.k.HD=function(){};
g.k.Jz=function(){};
g.k.Sq=function(){};
g.k.Rq=function(){};
g.k.SA=function(){};
g.k.Sr=function(){};
g.k.tD=function(){};g.w(x6,g.xT);x6.prototype.Rk=function(){return!1};
x6.prototype.load=function(){this.player.hideControls();this.j.show()};
x6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.wT("inline_preview",x6);})(_yt_player);
